spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${BLOLET_MAIL_USERNAME}
    password: ${BLOLET_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true