product:
  flyway:
    locations: classpath:db/migration/product/v1
    schema: product
    create-schemas: true
    baseline-on-migrate: true
    validate-on-migrate: false
    out-of-order: true
    history-table: flyway_schema_history_product
